// <auto-generated />
namespace Isdg.IsdgMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Albums : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Albums));
        
        string IMigrationMetadata.Id
        {
            get { return "201605040904181_Albums"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
