// <auto-generated />
namespace Isdg.IsdgMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SentEmail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SentEmail));
        
        string IMigrationMetadata.Id
        {
            get { return "201605111449515_SentEmail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
